name: sg_sabores_cliente
description: App Cliente do Sistema de Delivery SG Sabores.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  lottie: ^2.7.0

  # State Management
  provider: ^6.1.1
  get_it: ^7.6.4 # Injeção de dependência

  # Navigation
  go_router: ^12.1.1

  # Firebase
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_messaging: ^14.7.2

  # Authentication
  google_sign_in: ^6.1.5

  # HTTP
  dio: ^5.3.2

  # Utils
  intl: ^0.18.1
  uuid: ^4.1.0
  form_field_validator: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/ # Certifique-se que esta pasta existe na raiz do projeto